### ISSUE TITLE
Error: Cannot find ffmpeg

### ISSUE THREAD

**Issue by velesco** [SteTR/Emost-Bot#2]
Powering Up Voice Recognition Bot...
Voice Recognition Bot is Online
Guild 801400891323711488: created audio stream for Vasile
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find ffmpeg
    at D:\bumblebee\node_modules\fluent-ffmpeg\lib\processor.js:136:22
    at D:\bumblebee\node_modules\fluent-ffmpeg\lib\capabilities.js:123:9
    at wrapper (D:\bumblebee\node_modules\async\dist\async.js:271:20)
    at next (D:\bumblebee\node_modules\async\dist\async.js:5793:24)
    at D:\bumblebee\node_modules\async\dist\async.js:327:20
    at D:\bumblebee\node_modules\fluent-ffmpeg\lib\capabilities.js:116:11
    at D:\bumblebee\node_modules\fluent-ffmpeg\lib\utils.js:223:16
    at F (D:\bumblebee\node_modules\which\which.js:68:16)
    at E (D:\bumblebee\node_modules\which\which.js:80:29)
    at D:\bumblebee\node_modules\which\which.js:89:16
Emitted 'error' event on FfmpegCommand instance at:
    at emitEnd (D:\bumblebee\node_modules\fluent-ffmpeg\lib\processor.js:424:16)
    at D:\bumblebee\node_modules\fluent-ffmpeg\lib\processor.js:433:16
    at wrapper (D:\bumblebee\node_modules\async\dist\async.js:271:20)
    at next (D:\bumblebee\node_modules\async\dist\async.js:5793:24)
    at D:\bumblebee\node_modules\async\dist\async.js:327:20
    at wrapper (D:\bumblebee\node_modules\async\dist\async.js:271:20)
    at next (D:\bumblebee\node_modules\async\dist\async.js:5793:24)
    at D:\bumblebee\node_modules\async\dist\async.js:327:20
    at D:\bumblebee\node_modules\fluent-ffmpeg\lib\capabilities.js:519:16
    at D:\bumblebee\node_modules\fluent-ffmpeg\lib\processor.js:136:16

**Comment by velesco** [comment]
![image](https://user-images.githubusercontent.com/73293131/154243284-0d6241ba-2fac-449a-b463-1879d2ce493f.png)
